### ISSUE TITLE
Bug - Wrong repository

### ISSUE THREAD

**Issue by rkaldung** [znuny/ITSMCore#1]
### Expected behavior

Accessing the ITSM package repository without problems.

### Actual behavior

The repository can't be access because the default point to a non-existing host.

### How to reproduce

1. Install ITSMCore
2. Open package manager
3. Try to access the online repository

### Environment

- OS: n.a.
- Browser: n.a.
- Znuny/OTRS version 6.0.x / any version of ITSMCore 6.0.x

### Additional information

It's the system configuration [Package::RepositoryList](https://github.com/znuny/ITSMCore/blob/rel-6_0/Kernel/Config/Files/XML/FrameworkITSMCore.xml#L25) and should be fixed for new installations and during an upgrade to newer versions.

**Comment by dennykorsukewitz** [comment]
Fixed https://github.com/znuny/ITSMCore/blob/dev/Kernel/Config/Files/XML/FrameworkITSMCore.xml#L25

**Comment by rkaldung** [comment]
@dennykorsukewitz This needs to be fixed in 6.0 too
